"""Facebook Marketplace OAuth service implementation.

Implements OAuth 2.0 flow for Facebook Marketplace integration.
Handles token exchange, user info fetch, and page discovery.
"""

import logging
from datetime import UTC, datetime, timedelta
from urllib.parse import urlencode

import httpx

from prosell.core.config import get_settings
from prosell.domain.exceptions.facebook_exceptions import (
    FacebookNotConfiguredException,
    FacebookPageFetchException,
    FacebookTokenExchangeException,
    FacebookUserInfoFetchException,
)
from prosell.domain.ports.i_facebook_marketplace_service import (
    FacebookPageInfo,
    FacebookTokenExchangeResult,
    FacebookUserInfo,
    IFacebookMarketplaceOAuthService,
)

logger = logging.getLogger(__name__)

# Facebook Graph API version
GRAPH_API_VERSION = "v22.0"  # Latest stable version as of 2026

# Required OAuth scopes for Marketplace publishing
REQUIRED_SCOPES = [
    "pages_manage_posts",  # Create and manage posts
    "pages_read_engagement",  # Read engagement data
    "pages_manage_metadata",  # Manage page metadata
    "pages_read_user_content",  # Read user content
    "pages_manage_engagement",  # Manage engagement
]


class FacebookMarketplaceOAuthServiceImpl(IFacebookMarketplaceOAuthService):
    """Facebook Marketplace OAuth service implementation.

    Handles OAuth 2.0 flow for connecting Facebook accounts for Marketplace publishing.

    Architecture:
    - Adapter in Clean Architecture terminology
    - Implements IFacebookMarketplaceOAuthService port
    - Uses httpx.AsyncClient for non-blocking HTTP requests

    OAuth Flow:
    1. get_authorization_url(): Generate OAuth URL with state token
    2. User authorizes on Facebook
    3. exchange_code_for_token(): Exchange code for short-lived token
    4. exchange_for_long_lived_token(): Get 60-day token
    5. get_user_info(): Fetch user info
    6. get_user_pages(): Fetch user's pages
    """

    # Facebook OAuth endpoints
    OAUTH_DIALOG_URL = f"https://www.facebook.com/{GRAPH_API_VERSION}/dialog/oauth"
    TOKEN_EXCHANGE_URL = f"https://graph.facebook.com/{GRAPH_API_VERSION}/oauth/access_token"
    USER_INFO_URL = f"https://graph.facebook.com/{GRAPH_API_VERSION}/me"
    USER_PAGES_URL = f"https://graph.facebook.com/{GRAPH_API_VERSION}/me/accounts"

    def __init__(self) -> None:
        """Initialize Facebook OAuth service."""
        settings = get_settings()

        self.app_id = settings.facebook_oauth_app_id
        self.app_secret = settings.facebook_oauth_app_secret
        self.redirect_uri = settings.facebook_oauth_redirect_uri

        # HTTP client with timeout
        self.client = httpx.AsyncClient(timeout=30.0)

        logger.info("FacebookMarketplaceOAuthServiceImpl initialized")

    def _validate_config(self) -> None:
        """Validate Facebook OAuth credentials are configured.

        Called lazily on first use to allow DI wiring even when credentials
        are not set (e.g., feature_oauth_facebook=False environments).

        Raises:
            FacebookNotConfiguredException: If app_id or app_secret is missing.
        """
        if not self.app_id:
            raise FacebookNotConfiguredException("app_id")
        if not self.app_secret:
            raise FacebookNotConfiguredException("app_secret")

    async def get_authorization_url(self, state_token: str) -> str:
        """Generate Facebook OAuth authorization URL.

        Args:
            state_token: CSRF protection token (generated by use case)

        Returns:
            Full authorization URL to redirect user to

        Raises:
            FacebookNotConfiguredException: If Facebook OAuth credentials missing
        """
        self._validate_config()
        params = {
            "client_id": self.app_id,
            "redirect_uri": self.redirect_uri,
            "scope": ",".join(REQUIRED_SCOPES),
            "response_type": "code",
            "state": state_token,
        }

        url = f"{self.OAUTH_DIALOG_URL}?{urlencode(params)}"
        logger.info(f"Generated Facebook OAuth authorization URL with state={state_token[:8]}...")

        return url

    async def exchange_code_for_token(self, code: str) -> FacebookTokenExchangeResult:
        """Exchange authorization code for short-lived access token.

        Args:
            code: Authorization code from Facebook callback

        Returns:
            Token exchange result with short-lived token (1-hour expiry)

        Raises:
            FacebookTokenExchangeException: If token exchange fails
        """
        try:
            response = await self.client.get(
                self.TOKEN_EXCHANGE_URL,
                params={
                    "code": code,
                    "client_id": self.app_id,
                    "client_secret": self.app_secret,
                    "redirect_uri": self.redirect_uri,
                },
            )
            response.raise_for_status()

            data = response.json()

            access_token = data.get("access_token")
            if not access_token:
                raise FacebookTokenExchangeException("no_access_token_in_response")

            # Short-lived tokens expire in 1 hour
            expires_at = datetime.now(UTC) + timedelta(hours=1)

            logger.info("Successfully exchanged Facebook authorization code for short-lived token")

            return FacebookTokenExchangeResult(
                access_token=access_token,
                expires_at=expires_at,
                scopes=REQUIRED_SCOPES,
            )

        except httpx.HTTPStatusError as e:
            logger.error(
                f"Facebook token exchange failed: {e.response.status_code} - {e.response.text}"
            )
            raise FacebookTokenExchangeException("http_error") from e
        except Exception as e:
            logger.error(f"Unexpected error during token exchange: {e}")
            raise FacebookTokenExchangeException("unexpected_error") from e

    async def exchange_for_long_lived_token(
        self,
        short_lived_token: str,
    ) -> FacebookTokenExchangeResult:
        """Exchange short-lived token for long-lived (60-day) token.

        Args:
            short_lived_token: Short-lived access token (1-hour expiry)

        Returns:
            Long-lived token result with 60-day expiry

        Raises:
            FacebookTokenExchangeException: If token exchange fails
        """
        try:
            response = await self.client.get(
                self.TOKEN_EXCHANGE_URL,
                params={
                    "grant_type": "fb_exchange_token",
                    "client_id": self.app_id,
                    "client_secret": self.app_secret,
                    "fb_exchange_token": short_lived_token,
                },
            )
            response.raise_for_status()

            data = response.json()

            access_token = data.get("access_token")
            if not access_token:
                raise FacebookTokenExchangeException("no_access_token_in_response")

            # Long-lived tokens expire in 60 days
            expires_in_seconds = data.get("expires_in", 5184000)  # Default 60 days
            expires_at = datetime.now(UTC) + timedelta(seconds=expires_in_seconds)

            logger.info("Successfully exchanged short-lived token for long-lived token (60-day)")

            return FacebookTokenExchangeResult(
                access_token=access_token,
                expires_at=expires_at,
                scopes=REQUIRED_SCOPES,
            )

        except httpx.HTTPStatusError as e:
            logger.error(f"Long-lived token exchange failed: {e.response.status_code}")
            raise FacebookTokenExchangeException("long_lived_exchange_failed") from e
        except Exception as e:
            logger.error(f"Unexpected error during long-lived token exchange: {e}")
            raise FacebookTokenExchangeException("unexpected_error") from e

    async def get_user_info(self, access_token: str) -> FacebookUserInfo:
        """Get Facebook user info using access token.

        Args:
            access_token: Valid Facebook access token

        Returns:
            Facebook user info

        Raises:
            FacebookUserInfoFetchException: If user info fetch fails
        """
        try:
            response = await self.client.get(
                self.USER_INFO_URL,
                params={
                    "fields": "id,name,email",
                    "access_token": access_token,
                },
            )
            response.raise_for_status()

            data = response.json()

            logger.info(f"Successfully fetched user info for Facebook user: {data.get('id')}")

            return FacebookUserInfo(
                facebook_user_id=data["id"],
                name=data.get("name", ""),
                email=data.get("email"),
            )

        except httpx.HTTPStatusError as e:
            logger.error(f"Facebook user info fetch failed: {e.response.status_code}")
            raise FacebookUserInfoFetchException("http_error") from e
        except Exception as e:
            logger.error(f"Unexpected error fetching user info: {e}")
            raise FacebookUserInfoFetchException("unexpected_error") from e

    async def get_user_pages(self, access_token: str) -> list[FacebookPageInfo]:
        """Get all pages accessible to the user.

        Args:
            access_token: Valid Facebook user access token

        Returns:
            List of pages with page-specific access tokens

        Raises:
            FacebookPageFetchException: If page fetch fails
        """
        try:
            response = await self.client.get(
                self.USER_PAGES_URL,
                params={
                    "access_token": access_token,
                    "fields": "id,name,access_token,category,picture.width(512)",
                },
            )
            response.raise_for_status()

            data = response.json()
            pages_data = data.get("data", [])

            pages = []
            for page_data in pages_data:
                # Extract picture URL if available
                picture_url = None
                if page_data.get("picture"):
                    picture_url = page_data["picture"]["data"]["url"]

                pages.append(
                    FacebookPageInfo(
                        page_id=page_data["id"],
                        page_name=page_data["name"],
                        access_token=page_data["access_token"],
                        category=page_data.get("category"),
                        picture_url=picture_url,
                    )
                )

            logger.info(f"Successfully fetched {len(pages)} pages for user")

            return pages

        except httpx.HTTPStatusError as e:
            logger.error(f"Facebook page fetch failed: {e.response.status_code}")
            raise FacebookPageFetchException("http_error") from e
        except Exception as e:
            logger.error(f"Unexpected error fetching pages: {e}")
            raise FacebookPageFetchException("unexpected_error") from e

    async def refresh_page_token(
        self,
        page_id: str,
        user_access_token: str,
    ) -> str:
        """Refresh a page access token.

        Note: Page tokens don't auto-refresh like user tokens.
        This method re-fetches the page token from /me/accounts endpoint.

        Args:
            page_id: Facebook page ID
            user_access_token: Valid user access token

        Returns:
            New page access token

        Raises:
            FacebookTokenExchangeException: If token refresh fails
        """
        try:
            # Re-fetch all pages to get updated tokens
            pages = await self.get_user_pages(user_access_token)

            # Find the requested page
            for page in pages:
                if page.page_id == page_id:
                    logger.info(f"Successfully refreshed token for page {page_id}")
                    return page.access_token

            # Page not found
            raise FacebookTokenExchangeException("page_not_found")

        except Exception as e:
            logger.error(f"Failed to refresh page token for {page_id}: {e}")
            raise FacebookTokenExchangeException("refresh_failed") from e

    async def close(self) -> None:
        """Close HTTP client.

        Should be called when service is no longer needed.
        """
        await self.client.aclose()
