"""Integration tests: SqlAlchemyProductRepository must PERSIST thumbnail_image_key.

Regression-prevention for the catalog-image-perf work (intent
`260920-catalog-image-performanc`): the `thumbnail_image_key` column is
generated by the image-router pipeline, not by user PATCH. The
repository's `create()` (explicit ProductModel constructor) and
`update()` (field-by-field copy) must therefore write
`model.thumbnail_image_key` end-to-end so the pipeline's call to
`repo.update()` after generating the derivative actually persists the
key. Same defect class as the original `cover_image_key` regression:
the in-memory entity would look correct but the DB column would be
stale.

These tests go through the REAL repository + test DB — unit tests that
only mirror the entity cannot catch a persistence gap.

Requires the test DB running on port 5433.
"""

import pytest

from prosell.domain.entities.product import Product
from prosell.domain.value_objects.product_condition import ProductCondition
from prosell.infrastructure.repositories.product_repository_impl import (
    SqlAlchemyProductRepository,
)


def _keys(tenant_id) -> tuple[str, str, str]:
    base = f"orgs/{tenant_id}/vehicles"
    return f"{base}/a.jpg", f"{base}/b.jpg", f"{base}/thumb.webp"


@pytest.mark.asyncio
async def test_create_persists_thumbnail_image_key(db_session, test_organization, test_category):
    """create() must write thumbnail_image_key to the DB column.

    The image-router pipeline produces the derivative and calls
    create() with the product already carrying the new
    `thumbnail_image_key`. The repository MUST write it to the DB.
    """
    repo = SqlAlchemyProductRepository(db_session)
    tenant_id = test_organization.tenant_id
    key_a, key_b, thumb_key = _keys(tenant_id)

    product = Product.create(
        title="2017 Toyota Camry",
        price_cents=1_850_000,
        tenant_id=tenant_id,
        organization_id=test_organization.id,
        category_id=test_category.id,
        condition=ProductCondition.USED,
        attributes={},
        image_urls=[key_a, key_b],
        cover_image_key=key_a,
        thumbnail_image_key=thumb_key,
    )

    await repo.create(product)

    # Read back from the DB — the in-memory entity is not enough; we
    # need to prove the column was written.
    fetched = await repo.get_by_id(product.id, tenant_id)
    assert fetched is not None
    assert fetched.thumbnail_image_key == thumb_key


@pytest.mark.asyncio
async def test_update_persists_thumbnail_image_key(db_session, test_organization, test_category):
    """update() must write a changed thumbnail_image_key to the DB column.

    When the image-router regenerates the thumbnail derivative (e.g.,
    after a seller replaces the cover image), it loads the product,
    sets `thumbnail_image_key` to the new key, and calls `repo.update()`.
    The DB column MUST reflect the new value.
    """
    repo = SqlAlchemyProductRepository(db_session)
    tenant_id = test_organization.tenant_id
    key_a, key_b, thumb_v1 = _keys(tenant_id)
    thumb_v2 = f"orgs/{tenant_id}/vehicles/thumb-v2.webp"

    product = Product.create(
        title="2017 Toyota Camry",
        price_cents=1_850_000,
        tenant_id=tenant_id,
        organization_id=test_organization.id,
        category_id=test_category.id,
        condition=ProductCondition.USED,
        attributes={},
        image_urls=[key_a, key_b],
        cover_image_key=key_a,
        thumbnail_image_key=thumb_v1,
    )
    await repo.create(product)

    # Pipeline regenerates the derivative with a new key.
    product.thumbnail_image_key = thumb_v2
    await repo.update(product)

    fetched = await repo.get_by_id(product.id, tenant_id)
    assert fetched is not None
    assert fetched.thumbnail_image_key == thumb_v2, (
        "the new thumbnail key must survive the round-trip to the DB"
    )


@pytest.mark.asyncio
async def test_legacy_product_without_thumbnail_round_trips_as_none(
    db_session, test_organization, test_category
):
    """Legacy products (no thumbnail key yet) must persist and load as None.

    FR2.5 specifies the runtime fallback to `image_urls[0]` for products
    without a generated thumbnail. The DB column must default to NULL
    (no implicit default that would mask the fallback case).
    """
    repo = SqlAlchemyProductRepository(db_session)
    tenant_id = test_organization.tenant_id
    key_a, key_b, _ = _keys(tenant_id)

    product = Product.create(
        title="2015 Honda Civic (legacy)",
        price_cents=900_000,
        tenant_id=tenant_id,
        organization_id=test_organization.id,
        category_id=test_category.id,
        condition=ProductCondition.USED,
        attributes={},
        image_urls=[key_a, key_b],
        cover_image_key=key_a,
    )
    await repo.create(product)

    fetched = await repo.get_by_id(product.id, tenant_id)
    assert fetched is not None
    assert fetched.thumbnail_image_key is None


@pytest.mark.asyncio
async def test_cover_image_key_unchanged_by_thumbnail_round_trip(
    db_session, test_organization, test_category
):
    """Adding a thumbnail must not perturb the existing cover_image_key.

    Defense-in-depth: the two columns are independent by design (the
    cover is the gallery-cover selection, the thumbnail is the
    catalog-card derivative). The round-trip must preserve both
    values verbatim.
    """
    repo = SqlAlchemyProductRepository(db_session)
    tenant_id = test_organization.tenant_id
    key_a, key_b, thumb_key = _keys(tenant_id)

    product = Product.create(
        title="2018 Mazda CX-5",
        price_cents=2_500_000,
        tenant_id=tenant_id,
        organization_id=test_organization.id,
        category_id=test_category.id,
        condition=ProductCondition.USED,
        attributes={},
        image_urls=[key_a, key_b],
        cover_image_key=key_b,
        thumbnail_image_key=thumb_key,
    )
    await repo.create(product)

    fetched = await repo.get_by_id(product.id, tenant_id)
    assert fetched is not None
    assert fetched.cover_image_key == key_b
    assert fetched.thumbnail_image_key == thumb_key
