from collections.abc import AsyncGenerator
from uuid import UUID

import pytest
import pytest_asyncio
from sqlalchemy.ext.asyncio import AsyncSession

from prosell.infrastructure.models.category_model import CategoryModel
from prosell.infrastructure.models.organization_model import OrganizationModel
from prosell.infrastructure.models.role_model import RoleModel
from prosell.infrastructure.models.user_model import UserModel

TEST_DB_URL: str

async def system_roles(_session_engine) -> dict[str, RoleModel]: ...
@pytest_asyncio.fixture
async def db_session() -> AsyncGenerator[AsyncSession]: ...
@pytest_asyncio.fixture
async def test_organization(db_session: AsyncSession) -> AsyncGenerator[OrganizationModel]: ...
@pytest_asyncio.fixture
async def test_role(system_roles: dict[str, RoleModel]) -> RoleModel: ...
@pytest_asyncio.fixture
async def test_seller_role(system_roles: dict[str, RoleModel]) -> RoleModel: ...
@pytest_asyncio.fixture
async def test_manager_role(system_roles: dict[str, RoleModel]) -> RoleModel: ...
@pytest_asyncio.fixture
async def test_user(db_session: AsyncSession, test_organization: OrganizationModel, test_role: RoleModel) -> AsyncGenerator[UserModel]: ...
@pytest_asyncio.fixture
async def test_seller_user(db_session: AsyncSession, test_organization: OrganizationModel, test_seller_role: RoleModel) -> AsyncGenerator[UserModel]: ...
@pytest_asyncio.fixture
async def test_category(db_session: AsyncSession, test_organization: OrganizationModel) -> AsyncGenerator[CategoryModel]: ...
@pytest.fixture
def shared_tenant_id() -> UUID: ...
def disable_rate_limiting(monkeypatch: pytest.MonkeyPatch) -> None: ...
