"""Facebook Marketplace OAuth service interface (Port).

This service is specifically for Facebook OAuth for Marketplace integration,
separate from authentication OAuth (which is handled by IOAuthService).

Key differences:
- IOAuthService: OAuth for user login (creates/updates users)
- IFacebookMarketplaceOAuthService: OAuth for Marketplace publishing (stores tokens)
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime


@dataclass(frozen=True)
class FacebookPageInfo:
    """Facebook page information from Graph API.

    Attributes:
        page_id: Facebook page ID
        page_name: Page name
        access_token: Page access token (for publishing as page)
        category: Page category (e.g., "Vehicle Dealer")
        picture_url: Page profile picture URL
    """

    page_id: str
    page_name: str
    access_token: str
    category: str | None = None
    picture_url: str | None = None


@dataclass(frozen=True)
class FacebookTokenExchangeResult:
    """Result of Facebook token exchange.

    Attributes:
        access_token: Long-lived access token (60-day expiry)
        expires_at: Token expiration datetime
        scopes: Granted permissions
    """

    access_token: str
    expires_at: datetime
    scopes: list[str]


@dataclass(frozen=True)
class FacebookUserInfo:
    """Facebook user info from Graph API.

    Attributes:
        facebook_user_id: Facebook user ID
        name: Facebook user name
        email: Facebook email (optional)
    """

    facebook_user_id: str
    name: str
    email: str | None = None


class IFacebookMarketplaceOAuthService(ABC):
    """Facebook Marketplace OAuth service interface.

    Handles OAuth 2.0 flow for connecting Facebook accounts for Marketplace publishing.

    OAuth Flow:
    1. Vendedor clicks "Connect Facebook"
    2. Backend generates authorization URL with state token
    3. Vendedor authorizes on Facebook
    4. Facebook redirects to callback with code
    5. Backend exchanges code for long-lived token (60-day)
    6. Backend fetches vendedor's pages
    7. Backend stores encrypted tokens

    Required Scopes:
    - pages_manage_posts: Create and manage posts
    - pages_read_engagement: Read engagement data
    - pages_manage_metadata: Manage page metadata
    - pages_read_user_content: Read user content
    - pages_manage_engagement: Manage engagement
    """

    @abstractmethod
    async def get_authorization_url(
        self,
        state_token: str,
    ) -> str:
        """Generate Facebook OAuth authorization URL.

        Args:
            state_token: CSRF protection token (generated by use case)

        Returns:
            Full authorization URL to redirect user to

        Raises:
            FacebookNotConfiguredException: If Facebook OAuth credentials missing
        """
        pass

    @abstractmethod
    async def exchange_code_for_token(
        self,
        code: str,
    ) -> FacebookTokenExchangeResult:
        """Exchange authorization code for short-lived access token.

        Args:
            code: Authorization code from Facebook callback

        Returns:
            Token exchange result with short-lived token

        Raises:
            FacebookTokenExchangeException: If token exchange fails
        """
        pass

    @abstractmethod
    async def exchange_for_long_lived_token(
        self,
        short_lived_token: str,
    ) -> FacebookTokenExchangeResult:
        """Exchange short-lived token for long-lived (60-day) token.

        Args:
            short_lived_token: Short-lived access token (1-hour expiry)

        Returns:
            Long-lived token result with 60-day expiry

        Raises:
            FacebookTokenExchangeException: If token exchange fails
        """
        pass

    @abstractmethod
    async def get_user_info(
        self,
        access_token: str,
    ) -> FacebookUserInfo:
        """Get Facebook user info using access token.

        Args:
            access_token: Valid Facebook access token

        Returns:
            Facebook user info

        Raises:
            FacebookUserInfoFetchException: If user info fetch fails
        """
        pass

    @abstractmethod
    async def get_user_pages(
        self,
        access_token: str,
    ) -> list[FacebookPageInfo]:
        """Get all pages accessible to the user.

        Args:
            access_token: Valid Facebook user access token

        Returns:
            List of pages with page-specific access tokens

        Raises:
            FacebookPageFetchException: If page fetch fails
        """
        pass

    @abstractmethod
    async def refresh_page_token(
        self,
        page_id: str,
        user_access_token: str,
    ) -> str:
        """Refresh a page access token.

        Note: Page tokens don't auto-refresh like user tokens.
        This method re-fetches the page token from /me/accounts endpoint.

        Args:
            page_id: Facebook page ID
            user_access_token: Valid user access token

        Returns:
            New page access token

        Raises:
            FacebookTokenRefreshException: If token refresh fails
        """
        pass
