"""Create an organization: org + enabled verticals + optional owner invitation, atomically."""

from dataclasses import dataclass
from uuid import UUID, uuid4

from prosell.application.use_cases.organization.invite_organization_owner import (
    InviteOrganizationOwnerUseCase,
)
from prosell.domain.entities.organization import Organization
from prosell.domain.entities.organization_invitation import OrganizationInvitation
from prosell.domain.repositories.category_repository import AbstractCategoryRepository
from prosell.domain.repositories.organization_repository import AbstractOrganizationRepository
from prosell.domain.repositories.organization_vertical_repository import (
    AbstractOrganizationVerticalRepository,
)
from prosell.domain.repositories.user_repository import AbstractUserRepository


@dataclass(frozen=True)
class CreateOrganizationResult:
    """Result of creating an organization.

    `organization` is always present — its id is generated by Organization.create()
    and never faked from the invitation. `invitation` is None when the caller
    did not provide an `owner_email`.
    """

    organization: Organization
    invitation: OrganizationInvitation | None


class CreateOrganizationUseCase:
    """Staff-only: create a new organization, enable its verticals, optionally invite its owner.

    Atomic for free: the request-scoped session (`get_async_session`) commits
    once at the end of the request and rolls back the whole session
    on any unhandled exception, and every repository call here uses `.flush()`, never
    `.commit()`. So a failure at any step -- including email delivery inside
    InviteOrganizationOwnerUseCase -- already rolls back the org and vertical rows
    too, with no explicit transaction wrapping needed in the router. See
    `tests/integration/use_cases/test_create_organization_atomicity.py`.
    """

    def __init__(
        self,
        organization_repository: AbstractOrganizationRepository,
        vertical_repository: AbstractOrganizationVerticalRepository,
        user_repository: AbstractUserRepository,
        category_repository: AbstractCategoryRepository,
        invite_organization_owner_use_case: InviteOrganizationOwnerUseCase,
    ) -> None:
        self.organization_repository = organization_repository
        self.vertical_repository = vertical_repository
        self.user_repository = user_repository
        self.category_repository = category_repository
        self.invite_organization_owner_use_case = invite_organization_owner_use_case

    async def execute(
        self,
        name: str,
        vertical_ids: list[UUID],
        created_by_user_id: UUID,
        owner_email: str | None = None,
        inviter_name: str | None = None,
    ) -> CreateOrganizationResult:
        if not vertical_ids:
            raise ValueError("At least one vertical must be selected")

        for root_category_id in vertical_ids:
            category = await self.category_repository.get_by_id_cross_tenant(root_category_id)
            if category is None:
                raise ValueError(f"Unknown vertical id: {root_category_id}")
            if not category.is_active:
                raise ValueError(f"Inactive vertical id: {root_category_id}")

        # Create the org FIRST — organization_id is generated here and is
        # always real, independent of whether an invitation is issued next.
        tenant_id = uuid4()
        organization = Organization.create(
            name=name, tenant_id=tenant_id, creator_id=created_by_user_id
        )
        organization = await self.organization_repository.create(organization)

        for root_category_id in vertical_ids:
            await self.vertical_repository.enable(
                organization_id=organization.id, root_category_id=root_category_id
            )

        # If no owner_email was provided, the org exists without an invitation.
        if owner_email is None:
            return CreateOrganizationResult(organization=organization, invitation=None)

        normalized_email = owner_email.lower().strip()
        existing_user = await self.user_repository.get_by_email(normalized_email)
        if existing_user is not None and existing_user.deleted_at is None:
            raise ValueError("owner_email is already registered")

        invitation = await self.invite_organization_owner_use_case.execute(
            organization_id=organization.id,
            organization_name=organization.name,
            email=normalized_email,
            tenant_id=tenant_id,
            inviter_name=inviter_name or "",
            created_by_user_id=created_by_user_id,
        )

        return CreateOrganizationResult(organization=organization, invitation=invitation)
