"""DTOs for organization creation (Task 12)."""

from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, EmailStr, Field, StringConstraints


class BrokerInput(BaseModel):
    """Broker to add at org creation time."""

    name: str
    email: EmailStr
    phone: str | None = None


class CreateOrganizationRequest(BaseModel):
    """Request body for POST /admin/organizations.

    `owner_email` is optional: if provided, an invitation is issued so the
    org owner can register and access the platform. If omitted, the org is
    created without an invitation — common case when ProSell staff manages
    the org's inventory and sales directly until the org needs its own user.
    """

    name: Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=255)]
    vertical_ids: list[UUID]
    owner_email: EmailStr | None = None
    brokers: list[BrokerInput] = Field(
        default_factory=list,  # Optional: add brokers at creation time
    )


class CreateOrganizationResponse(BaseModel):
    """Response body for POST /admin/organizations and the resend-invitation endpoint.

    When `owner_email` was omitted from the request, invitation fields are null —
    the org still has a real `organization_id` generated by Organization.create().
    """

    organization_id: UUID
    invitation_id: UUID | None = None
    email: str | None = None
    status: str | None = None
