"""create_roles_and_user_roles_tables

Revision ID: 787a09dad21b
Revises: vehicle_vin_required_20260625
Create Date: 2026-06-28 08:10:10.682304

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "787a09dad21b"
down_revision: str | Sequence[str] | None = "vehicle_vin_required_20260625"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("role_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system_role", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_type"),
    )
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_roles_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "user_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("token_type", sa.String(length=50), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_tokens_token"), ["token"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "assigned_at", sa.DateTime(timezone=True), server_default="now()", nullable=False
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_roles_role_id"), ["role_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_roles_user_id"), ["user_id"], unique=False)

    op.create_table(
        "wallets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("balance_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("wallets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_wallets_org_id"), ["org_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_wallets_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "team_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("commission_rate", sa.Float(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_team_members_team_id"), ["team_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_team_members_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_team_members_user_id"), ["user_id"], unique=False)

    op.create_table(
        "wallet_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("balance_after_cents", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("wallet_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wallet_transactions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wallet_transactions_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wallet_transactions_wallet_id"), ["wallet_id"], unique=False
        )

    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointments_tenant_id_dealer_id"))
        batch_op.drop_index(batch_op.f("ix_appointments_tenant_id_dealer_id_scheduled_at"))
        batch_op.create_index(batch_op.f("ix_appointments_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("branches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dealers_slug"))
        batch_op.drop_index(batch_op.f("ix_dealers_tenant_id"))
        batch_op.create_index(batch_op.f("ix_branches_slug"), ["slug"], unique=False)
        batch_op.create_index(batch_op.f("ix_branches_tenant_id"), ["tenant_id"], unique=False)

    with op.batch_alter_table("bulk_upload_errors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bulk_upload_errors_expires_at"))

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_categories_attribute_schema_gin"), postgresql_using="gin"
        )

    with op.batch_alter_table("lead_audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lead_audit_log_tenant_id_created_at"))

    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leads_tenant_id_created_at"))
        batch_op.drop_index(batch_op.f("ix_leads_tenant_id_status"))
        batch_op.drop_index(batch_op.f("ix_leads_vehicle_id"))
        batch_op.create_index(batch_op.f("ix_leads_product_id"), ["product_id"], unique=False)

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_is_read"))
        batch_op.drop_index(batch_op.f("ix_notifications_user_created"))

    with op.batch_alter_table("organization_invitations", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ux_organization_invitations_org_email_pending"),
            postgresql_where="((status)::text = 'pending'::text)",
        )

    with op.batch_alter_table("user_branches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_dealers_user_id"))
        batch_op.create_index(batch_op.f("ix_user_branches_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_branches_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("users_email_key"), type_="unique")
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=False)
        batch_op.create_unique_constraint(
            batch_op.f("users_email_key"), ["email"], postgresql_nulls_not_distinct=False
        )

    with op.batch_alter_table("user_branches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_branches_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_branches_tenant_id"))
        batch_op.create_index(batch_op.f("ix_user_dealers_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("organization_invitations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ux_organization_invitations_org_email_pending"),
            ["organization_id", "email"],
            unique=True,
            postgresql_where="((status)::text = 'pending'::text)",
        )

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_user_created"), ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_is_read"), ["is_read"], unique=False)

    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leads_product_id"))
        batch_op.create_index(batch_op.f("ix_leads_vehicle_id"), ["product_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_leads_tenant_id_status"), ["tenant_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_leads_tenant_id_created_at"),
            ["tenant_id", sa.literal_column("created_at DESC")],
            unique=False,
        )

    with op.batch_alter_table("lead_audit_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lead_audit_log_tenant_id_created_at"),
            ["tenant_id", sa.literal_column("created_at DESC")],
            unique=False,
        )

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_categories_attribute_schema_gin"),
            ["attribute_schema"],
            unique=False,
            postgresql_using="gin",
        )

    with op.batch_alter_table("bulk_upload_errors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bulk_upload_errors_expires_at"), ["expires_at"], unique=False
        )

    with op.batch_alter_table("branches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_branches_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_branches_slug"))
        batch_op.create_index(batch_op.f("ix_dealers_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_dealers_slug"), ["slug"], unique=False)

    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointments_user_id"))
        batch_op.create_index(
            batch_op.f("ix_appointments_tenant_id_dealer_id_scheduled_at"),
            ["tenant_id", "user_id", "scheduled_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_appointments_tenant_id_dealer_id"),
            ["tenant_id", "user_id"],
            unique=False,
        )

    with op.batch_alter_table("wallet_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wallet_transactions_wallet_id"))
        batch_op.drop_index(batch_op.f("ix_wallet_transactions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_wallet_transactions_created_at"))

    op.drop_table("wallet_transactions")
    with op.batch_alter_table("team_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_team_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_team_members_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_team_members_team_id"))

    op.drop_table("team_members")
    with op.batch_alter_table("wallets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wallets_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_wallets_org_id"))

    op.drop_table("wallets")
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_roles_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_roles_role_id"))

    op.drop_table("user_roles")
    with op.batch_alter_table("user_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_tokens_token"))

    op.drop_table("user_tokens")
    with op.batch_alter_table("roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_roles_tenant_id"))

    op.drop_table("roles")
    # ### end Alembic commands ###
